### ISSUE TITLE
Patient profession (ammatti)

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#1]
There are national requirements for storing profession information. I can't find this from the base spec. Should we include this in the profile? 

For details see eg. [hilmo-guide](https://www.julkari.fi/handle/10024/138288) Chapter 3.2.

**Comment by mikajylha** [comment]
Hilmo guide: 

Tietosisältö ja luokituksetHilmo-opas 2020 3.2 Asiakkaan perustiedot
•  Ilmoitetaan TK - Ammattiluokitus 2001 -luokituksen mukaisesti

https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=353&versionKey=431

**Comment by Marvasuo** [comment]
Any ideas which is the correct system for extension:
https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=353&versionKey=431
OR
http://www.tilastokeskus.fi/meta/luokitukset/ammatti/001-2001/index.html

Or maybe something else?

**Comment by Marvasuo** [comment]
Actually if we use Coding data type then system could be 1.2.246.537.6.74...
