### ISSUE TITLE
Kela: Immunization encounter referenssin täydennys

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#130]
Immunization ja siellä "encounter" : {
"reference" : "Encounter/id-for-palvelutapahtuma"
 Eli voisiko viitata palvelutapahtumaan reference-elementin sijaan suoraan palvelutapahtumaan identifier-elementistä? Jos voi, niin sen voisi tuoda esiin oppaassa.

**Comment by mikajylha** [comment]
Korjausehdotus: Example Encounter: Encounter that is part of palvelutapahtuma -esimerkkiin voisi laittaa narratiiviosioon tekstin että viittaus type + identifier -tyylillä muista resursseista on myös ok.

**Comment by mikatuomainen** [comment]
ks. #129
