### ISSUE TITLE
Laajennus RegisterSpecifier: Rekisterin tarkenteen tietotyyppi + rakenne

### ISSUE THREAD

**Issue by mikatuomainen** [fhir-fi/finnish-base-profiles#135]
https://fhir.fi/finnish-base-profiles/StructureDefinition-register-specifier.html

**Vanha huomio kuvaukseen käyttötarkoituksesta:**
Tietoa käytetään myös tietojen tietosisällön metatietona kun rekisterinä on työterveyshuolto, ei siis vain Kanta hauissa (tästä kommentoitu jo aiemminkin). Näiden dokumentoinnit löytyy näistä:

- Potilastiedon arkiston Medical Records  -sanomat, kappale 7.2.3 (MR näkökulma)
- Potilastiedon arkiston CDA R2 Header, kappale 2.4.21 (CDA R2 näkökulma)

Tietysti FHIR maailmaan siirryttäessä kyse ei ole enää MR hauista tai CDA R2:sta, vaan Kanta Potilastiedon arkiston hauista ja tietosisällöistä.

**Uusi huomio laajennuksen tietotyypistä**:
Laajennuksen RegisterSpecifier tietotyyppinä on string. Sen pitäisi olla Identifier, että voi antaa tarkenteen halutulla tavalla. Alla vaihtoehdot, jotka rekisterin tarkenteessa pitää pystyä antamaan (tämä poimittu Potilastiedon arkiston Medical Records dokumentista):

"_Rekisterintarkenne-kenttä on tyypiltään II ja siinä välitetään työnantajan yksilöintitunnus, joka on muodostettu työnantajan y-tunnuksesta.Tilanteissa, joissa y-tunnusta ei ole olemassa, voidaan käyttää virallista henkilötunnusta tai työterveyspalvelunantajakohtaisesti yksilöivää työnantajan numeroa.

Esimerkki: y-tunnus (root + extension käyttö):
<hl7fi:patientRegistrySpecifier root="1.2.246.10.1234567"/>
tai
<hl7fi:patientRegistrySpecifier extension="123456-7" root="1.2.246.10"/>

Tarkenteen nimi:
<hl7fi:patientRegistrySpecifierName>Työnantaja Oy</hl7fi:patientRegistrySpecifierName>

Henkilötunnusta käytettäessä::
<hl7fi:patientRegistrySpecifier extension="010144-123X" root="1.2.246.21"/>

Henkilötunnusta käytettäessä tarkenteen nimenä henkilön nimi:
<hl7fi:patientRegistrySpecifierName>Matti Meikäläinen</hl7fi:patientRegistrySpecifierName>

Y-tunnuksettomalle työnantajayritykselle muodostetaan rekisterintarkenne THL:n OID-avaruuteen (537). Solmuluokkaa 30 seuraa työterveyspalvelunantajan yksilöintitunnus (palvelunantajan OID:n yksilöivä osa, esim. y-tunnus ilman väliviivaa) sekä työnantaja-asiakkaan numeerinen yksilöintitunnus palvelunantajan järjestelmässä

<hl7fi:patientRegistrySpecifier root="1.2.246.537.30.2345678.11"/>

Tarkenteen nimi:
<hl7fi:patientRegistrySpecifierName>Employer Ltd</hl7fi:patientRegistrySpecifierName>_"

Jos ja kun tietotyyppiksi muutetaan Identifier, niin pitää huomioida miten edellä kuvatut kolme eri tunnistetta käytännössä tietotyypissä annetaan, varmaan kannattaa antaa aina erikseen systemissä nimiavaruus ja valuessa sitten varsinainen arvo, esim. näin:

Y-tunnus:
system: "1.2.246.10", value: "123456-7"

Henkilötunnus:
system: "1.2.246.21", value: "010144-123X" 

Y-tunnukseton työnantajayritys:
system: "1.2.246.537.30", value: "2345678.11"

Rekisterin tarkenteeseen liittyy myös tarkenteen nimi. Se ei ole välttämätön Kanta toiminnallisuuksien näkökulmasta mutta jos tietoa halutaan näyttää käyttöliittymissä, niin vaatii hetun perusteella nimen selvittämisen/y-tunnuksella yrityksen nimen selvittämisen. Y tunnuksemattoman nimeähän ei voi oikein selvittää mitenkään pelkän tunnisteen perusteella. Jos nimi otetaan mukaan -> onko erillinen laajennus vai complex laajennus, jossa tunniste ja nimi erillisinä.

**Comment by mrinnetmaki** [comment]
Hyvää settiä!

Pikaisena kommenttina, `system`-arvot olisivat paljon kivempia urleina kuin oideina... Osaatko @mikatuomainen sanoa löytyisikö joitakin url-vastineita?

**Comment by mikatuomainen** [comment]
Tarkenteen nimeä voisi myös harkita laajennukseen, ei välttämättä pakollinen ja voihan tuota laajennusta sitten tarvittaessa laajentaa. 

Ja laajennuksen konteksti taitaa edelleen puuttua (Provenance?).

**Comment by mrinnetmaki** [comment]
Fixed in #166.
