### ISSUE TITLE
Kuvaus siitä miten edunvalvoja esitetään

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#14]
Miten näkyy patient resurssissa? Tekstuaalinen kuvaus riittää.

**Comment by mrinnetmaki** [comment]
@Marvasuo had an idea described here: https://github.com/fhir-fi/finnish-base-profiles/blob/descriptions-for-patient-profile/input/pagecontent/StructureDefinition-FinnishCorePatient-intro.md#presenting-guardian-information

**Comment by mikajylha** [comment]
#17
