### ISSUE TITLE
Kela: Provenance luku 8.18.1

### ISSUE THREAD

**Issue by mrinnetmaki** [fhir-fi/finnish-base-profiles#141]
perustelu: laajennukset registerTypeCode ja registerSpecifier ovat nyt Provanance alla, pitäisi olla rekisterinpitäjään kuvaavan Organization resurssin laajennuksia.
 						
korjausehdotus: em. laajennukset pois Provenance profiilista ja siirrettävä Organization profiiliin, johon viitataan Provenancesta (tarvitaan siis Provenancen slaissaus + ehkä jopa rekisterinpitäjä tietoa kuvaava Organization profiilii)

**Comment by mrinnetmaki** [comment]
@mikajylha ?

**Comment by mrinnetmaki** [comment]
See discussion in https://github.com/fhir-fi/finnish-base-profiles/issues/88#issuecomment-1674838533

**Comment by mikatuomainen** [comment]
Tätä on pyöritelty nyt suuntaan ja toiseen eri foorumeilla. Mikä on näiden keskusteluiden lopputulema ja mihin suuntaan tätä ollaan viemässä?

**Comment by mikajylha** [comment]
#135
