### ISSUE TITLE
Kela: Luku 1.2

### ISSUE THREAD

**Issue by mrinnetmaki** [fhir-fi/finnish-base-profiles#143]
Luku 1.2: ”In many cases, the HL7 FHIR standard allows for several ways to implement a functionality. There are increasing concerns that without a coordinated approach implementers will choose different ways to implement some features, and this will lead to challenges for interoperability. This implementation guide attempts to define a consensus within the Finnish FHIR implementers on which ways we have considered the best fit for use cases in Finland.”
tekstissä mainitaan functionality, käytännössä perusprofiileissa otetaan kantaa vain tietosisältöihin (data content), ei miten tietoja liikutellaan kohdistettava teksti vain tietosisältöihin, toiminnallisuuttahan tässä oppaassa ei määritellä lainkaan

**Comment by mrinnetmaki** [comment]
Tuo perustuu siis alkuperäiseen toimeksiantoon ja siinä ilmaistuun pelkoon siitä, että eri toimijat toteuttavat FHIR-standardia toisistaan poikkeavilla tavoilla.

**Comment by mrinnetmaki** [comment]
Osaisitko vaihtoehtoisesti @mikatuomainen avata sitä, mikä väärinymmärryksen riski tuossa on ja mitä haittaa siitä aiheutuu?

**Comment by mikatuomainen** [comment]
Nythän on niin, että tässä perusprofiilit soveltamisoppaassa on kuvattu profiileja eli käytännössä miten FHIR resursseilla esitetään tietoja. Mutta varsinaiset toiminnallisuudet tietojen tallentamiseen, korjaamiseen, poistamiseen ja hakemiseen puuttuvat tai millaisilla rakenteilla niitä siirretään. Eli "functionality" tästä puuttuu ymmärtääkseni kokonaan. Jos "functionality" tarkoittaa jotain muuta, niin kommentti turha.
