### ISSUE TITLE
RegisterTypeCode: laajennuksen konteksti puuttuu

### ISSUE THREAD

**Issue by mikatuomainen** [fhir-fi/finnish-base-profiles#163]
Laajennuksen konteksti taitaa edelleen puuttua (Provenance?).

Lisäksi tuolla "TODO what is the system?" 

Käytettävät systemit näyttävät olevan Provenance esimerkissä:
https://fhir.fi/finnish-base-profiles/Provenance-id-for-provenance-1.html
ja ne ovat
- PTA: 1.2.246.537.5.40150.2009
- SHA: 1.2.246.537.6.1264.201701

**Comment by mikajylha** [comment]
Asiaan liittyy issue #88, joka saattaa muuttaa Provenancea merkittävästi erilaiseksi. Asia selvityksessä.

**Comment by mrinnetmaki** [comment]
Register type and register specifier were left out of the base profiles, for now. See https://www.hl7.fi/fhir/finnish-base-profiles/1.0.0/StructureDefinition-fi-base-information-custodian.html#how-to-communicate-kanta-information-custodian-and-register-information
