### ISSUE TITLE
Procedure examples lack code system version infromation

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#175]
code.coding[0] = urn:oid:1.2.246.537.6.2#JFA16

procedureColonomy.fsh and procedurePartOfMainProcedure.fsh lack info that they are from version 1.2.246.537.6.2.2007.

They should use the pipe syntax like in diagnosis examples:
`* code.coding = urn:oid:1.2.246.537.6.1|1999#H36.03`

**Comment by mrinnetmaki** [comment]
Care to create a pull request too, @mikajylha?
