### ISSUE TITLE
Patient-resurssin kehitys

### ISSUE THREAD

**Issue by mrinnetmaki** [fhir-fi/finnish-base-profiles#2]
Muistio kokouksesta:

* Tehdään mahdollisimman salliva profiili, ei turhia rajoitteita
* Hetun osalta voitaisiin tehdä slice, jossa official identifierille määrättäisiin hetun oid
* Ammatille tarvinnee laajennoksen (Mika J teki jo [issuen](#1))
* Turvakielto olisi hyödyllinen ominaisuus - ehkä meta-tägin security-osuuteen? Käytännössä vain boolean ja kenties päättymisaika. * * Pohjoismainen yhteistyö? Ruotsin perusprofiilissa vain nimeä, identifieriä ja postinumeroa.
* Edunvalvoja?
  * Link, RelatedPatient
* Yhteyshenkilönä organisaatio?
* Kielitiedot (asiointikieli, äidinkieli, tarvitaanko tulkkausta?)
  * Tulkkaus voi hyvinkin olla tilannekohtaista?
  * patient.interpreterRequired-laajennos saatavilla: http://hl7.org/fhir/R4/patient-profiles.html, http://hl7.org/fhir/R4/extension-patient-interpreterrequired.html.  
@Marvasuo jatkaa tämän kanssa.

**Comment by mrinnetmaki** [comment]
Tanskassa turvakielto on toteutettu `meta` / `security` -tavalla. http://build.fhir.org/ig/hl7dk/dk-core/StructureDefinition-dk-core-patient.html#use-of-security-label-on-patients

**Comment by mrinnetmaki** [comment]
Norjalaisilta en löytänyt turvakieltoa, mutta identifierille on tehty slice ja joitakin muitakin laajennoksia löytyy. https://simplifier.net/hl7norwayno-basis/nobasispatient

**Comment by mrinnetmaki** [comment]
Yritin löytää ruotsalaista potilaan perusprofiilia, niin tuli vastaan tällainen: https://simplifier.net/CambioR4/patient-populationRegistrationCounty.

Ruotsalaisella potilastietojärjestelmävalmistaja Cambiolla on siis määriteltynä laajennos kotikunnan kertomiselle.

**Comment by mrinnetmaki** [comment]
Löysin ruotsalaisilta lääkityslistaprojektista tuollaisen: https://simplifier.net/swedishnationalmedicationlist/security-labels

**Comment by Marvasuo** [comment]
Edunvalvojan ja organisaatio yhteyshenkilönä voisi käyttää RelatedPerson resurssia mutta sen relationship parametrin koodisto ei tarjoa kovin hyviä työkaluja ns. lainvoimaisuuden ilmaisemiseksi. Resurssi itsessään kyllä kertoo, että sitä voi käyttää edunvalvojan (guardian) kuvaamiseen.

**Comment by mrinnetmaki** [comment]
Is there perhaps a problem with the value set listed at http://hl7.org/fhir/R4B/valueset-relatedperson-relationshiptype.html?

I would have expected to see roles from https://terminology.hl7.org/3.1.0/CodeSystem-v3-RoleCode.html like `RESPRSN`, `GUADLTM`, `GUARD`, `POWATT`, `DPOWATT`, `HPOWATT`, `SPOWATT`, etc. ...

**Comment by mrinnetmaki** [comment]
There is an IG by Swedish EHR vendors published at http://build.fhir.org/ig/SvenskaIndustriProfiler/fhir/branches/master/StructureDefinition-PatientSEVendorLite.html.

**Comment by Marvasuo** [comment]
> Is there perhaps a problem with the value set listed at http://hl7.org/fhir/R4B/valueset-relatedperson-relationshiptype.html?
> 
> I would have expected to see roles from https://terminology.hl7.org/3.1.0/CodeSystem-v3-RoleCode.html like `RESPRSN`, `GUADLTM`, `GUARD`, `POWATT`, `DPOWATT`, `HPOWATT`, `SPOWATT`, etc. ...

I didn't realize that the PatientRelationshipType value set list doesn't show all of codes presented in these included code systems. Since this can be represented with this value set, use of relatedPerson resource could be instructed verbally in IG. Unless we want to define a certain value to be used in this situation.
