### ISSUE TITLE
Condition resurssi (encounter-diagnosis)

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#4]
Tarkennus: Conditionista on se toinen category: problem-list-item, mutta tämä issue koskettaa enemmän encounter-diagnosis -asiaa. En ole vielä pohtinut, millä tavalla tämä suhteutuu problem-list -puoleen.

## Tietosisällön laajuus
Voidaanko tavoitella samaa laajuutta mikä HILMOn ja potilastiedon arkiston diagnoosi määrittelyissä? Tämä vaikuttaisi vaativan extensioneja. 

Mitä Conditionilla halutaan ilmaista? Pelkkiä diagnooseja vai lisäksi myös käyntisyitä? Miten erotellaan diagnoosi ja käyntisyy toisistaan?

## Mallinnus

code-kenttään diagnoosin syykoodi (tai käyntisyyn ainokainen koodi). Voisiko mennä näin?

``` json
"code": {
    "coding": [
      {
        "system": "urn:oid:1.2.246.537.6.1.1999",
        "code": "A00.1",
        "display": "Klassinen kolera"
      }
    ]
  },
```

Seuraavat voisi määritellä (luultavasti vaativat laajennusta):
* oire-koodi (jos oire-syy pari tai syy-oire pari)
* e-koodi
* ulkoinen syy
* tapaturmatyyppi
* liikuntalaji
* lääke (atc)
* tietolähde
* varmuusaste
* pysyvyys
* ensisijaisuus

Entäs miten mallinnetaan päättyminen, mukaan lukien päättymisen syy?

## Mäppäys

Toteaja voidaan ilmaista participant:lla jonka function on [author](http://terminology.hl7.org/4.0.0/CodeSystem-provenance-participant-type.html#provenance-participant-type-author)

## Koodistot
Koodistojen osalta kansallisesti vaaditut icd-10 ja ICPC. Lisäksi varmaan snomed myös. 

## Ongelmat
* [ ] Päättäjälle ei löydy funktiokoodia (kts. author)

**Comment by mikajylha** [comment]
ICD-10 ja ICPC-2 vastaavuuden voi hoitaa code.coding -toistumalla

**Comment by mikatuomainen** [comment]
Tuossapa suora linkki "ICD dual coding" asiaan, löytyy ihan FHIR speksistä:
[http://hl7.org/fhir/R4/icd.html ](url)

Tuonne vähän vaikea eksyä mutta jos menee FHIR speksin dokumentaatioon niin tällä polulla tuonne pääseen
Documentation -> Terminologies (Complex Code Systems) -> ICD-X, laitoin tämän tähän jos haluaa perehtyä koko hommaan ylhäältä-alaspäin.

chat.fhir.org:sta löytynee myös aika paljon keskustelua tuohon aiheeseen liittyen. 

Kanta-kontekstissa tosiaan yhdistelmäkoodit on nyt purettu omikse osikseen ja rakenteisessa osuudessa ei mene yhdistelmäkoodeja. Jotenkin omaan makuun se selkeytti asioita, en tiedä menikö sitten käytännössä niin. Mutta tuossa FHIRin dual coding kohdassahan taasen mahdollistetaan yhteen code-elementtiin kahden koodin viennin. Mutta aika sekavasti, sillä taitaa sallia nuo koodit ilman välimerkkejä ja välimerkein (ilmeisesti Saksassa piti ehdottomasti saada välitettyä myös nuo välimerkit).

**Comment by mikatuomainen** [comment]
Tietosisällön laajuudesta/scopesta: tässä issuessa keskitytään diagnooseihin (ja käyntisyihin). Mutta sisältääkös Condition FHIRsssa muutakin kuin diagnoosit. Näin olen ainakin ymmärtänyt mutta oma substanssiosaaminen on tässä vähän rajoitteena. Haen tällä kommentilla sitä, että voidaanko Condition profiloinnissa rajautau vain diagnoosien (ja käyntisyiden) tietosisältöihin? Vai pitäisikö huomioida muutakin? Itse en osaa siis vastata esittämiini kysymyksiin.
