### ISSUE TITLE
Procedure

### ISSUE THREAD

**Issue by mikajylha** [fhir-fi/finnish-base-profiles#5]
Miten mallinnetaan toimenpiteen lisätoimenpiteet? 

Esim. "ZXC96 Robotin käyttö leikkauksessa". Näitä voi olla yhdellä toimenpiteellä monta.

**Comment by Marvasuo** [comment]
Onnistuuko pohjoismaalaisen toimepideluokituksen mukaiset merkinnät ylipäätään? Äkkiseltään näytti minun silmään siltä, että Procedure code tukee vain SNOMED CT koodistoa. Käytetäänkö vain tekstikuvausta?
https://www.hl7.org/fhir/procedure-definitions.html#Procedure.code
