### ISSUE TITLE
Should the colon biopsy procedure be an example of FiBaseProcedure?

### ISSUE THREAD

**Issue by mrinnetmaki** [fhir-fi/finnish-base-profiles#59]
Currently one of the examples is marked as an example of the base FHIR resource, not the profile specified in this implementation guide. Therefore this example is not listed as one of the examples of the FiBaseProcedure profile. Is this intentional?

https://github.com/fhir-fi/finnish-base-profiles/blob/master/input/fsh/examples/procedurePartOfMainProcedure.fsh#L2

**Comment by Marvasuo** [comment]
Good catch! It should be FiBaseProcedure. I'll fix this right away.
