### ISSUE TITLE
Condition.code.display improperly constrained to codeset value

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#79]
[When name differs from code.display](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-condition.html#when-name-differs-from-codedisplay)

>  code.display MUST be the original name from the codesystem and code.text MAY contain adjusted name for the diagnosis.

In Epic's [current FHIR implementation of conditon](https://fhir.epic.com/Specifications?api=950), we build code.display from the user-facing display name and do not constrain it to the codeset value. We do not populate code.name. Do we really need to constrain the display name if there's a codeset?

**Comment by jpriebe-epic** [comment]
> When using Finnish ICD-10, code MUST NOT contain special characters (+ after the code and * before code indicates symptom)

Also, it's a bit weird that we exclude special characters in a FHIR specification. We're already constrained to the codeset do we need to call out that codeset values can't include special characters?

**Comment by mrinnetmaki** [comment]
> > When using Finnish ICD-10, code MUST NOT contain special characters (+ after the code and * before code indicates symptom)
> 
> Also, it's a bit weird that we exclude special characters in a FHIR specification. We're already constrained to the codeset do we need to call out that codeset values can't include special characters?

I think this refers to (or attempts to refer to?) the `dagger and asterix` syntax, some insights here: http://hl7.org/fhir/R4/icd.html#4.3.11.3.1.

I personally don't have any more detailed view on this. Agree the description should be clearer.

**Comment by jpriebe-epic** [comment]
Dual coding - might be better to say that the FI FHIR profile doesn't support dual coding as defined in the R4 spec you listed

Any response on the display name? This constraint seems unneeded and outside the spec, and will be burdensome to support.

**Comment by jpriebe-epic** [comment]
Yeah you're totally right that the standard says display matches codeset.

On further review Epic does in fact import the codeset names into the database field that ends up populating our condition resource. So the name served in FHIR should match what's in the original codeset when imported.

It's not super strictly controlled that name conforms to codeset, system admins can override it but they rarely do so.

No further issues in this ticket.
