### ISSUE TITLE
Condition examples should be in examples section

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#80]
[Condition](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-condition.html#diagnosis-code-reason)

[type of sport in injury cases](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-condition.html#type-of-sport-in-injury-cases)

[Endocrinological Disorder](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-condition.html#endocrinological-disorder)

Both of these should be examples in the [examples section](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-condition-examples.html)

**Comment by mrinnetmaki** [comment]
Agreed, and as said in the IG:

> TODO add example.

:)

**Comment by jpriebe-epic** [comment]
Are these actually proposed extensions, or meant to be examples? If they're extensions, I'm curious about the use cases and taking a second look at supporting them via standard fields.

**Comment by mikajylha** [comment]
#91 might be enough to fix this issue.

**Comment by jpriebe-epic** [comment]
I've got some more comments about the extensions you added, but I'll open a new issue
