### ISSUE TITLE
Practitioner identifiers

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#82]
[Practioner ID Slices](https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-practitioner-definitions.html)

>Practitioner.identifier:Terhikki

Ok. We store this ID in Apotti and can support this today.

> Practitioner.identifier:SSN

Is this just HETU?

> Practitioner.identifier:SV

Can you give more info on this identifier? I want to make sure we support this today in Apotti's system

**Comment by Marvasuo** [comment]
Actually there is a minor issue regarding SSN abbreviation. That refers to "Social Security Number" which is not the correct definition for HETU. PIC (like in Patient profile) should be used in here and it stands for "Personal Identifier Code". https://dvv.fi/en/personal-identity-code
We have already acknowledged this error and decided to fix it soon.

Here you can find a definition for SV-number. Unfortunately the page is in Finnish but the identifier is explained under Yksilöintitunnus heading.
https://www.valvira.fi/valvira/rekisterit/terveydenhuollon_ammattihenkilot

**Comment by jpriebe-epic** [comment]
Ah yes - we call this SV number the "Valvira ID" in Apotti. All 3 identifiers are stored and supported by Apotti then. 

Yeah SSN is a very US concept, broadly meaning "national identifier".

**Comment by jpriebe-epic** [comment]
Nothing else to track here once you address the "SSN" thing you mentioned.
