### ISSUE TITLE
Patient Identifiers

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#83]
https://www.hl7.fi/fhir/finnish-base-profiles/1.0-rc2/StructureDefinition-fi-base-patient.html

Format looks weird on this page. 

PIC looks like a HETU (Finnish national ID), but I haven't heard it referred to this way. Maybe we're just weird in Apotti referring to it this way, but probably worth adding a synonym. 

We support this in Apotti today.

**Comment by Marvasuo** [comment]
PIC stands for "Personal Identifier Code". It is the correct abbreviation for HETU.
https://dvv.fi/en/personal-identity-code

**Comment by jpriebe-epic** [comment]
Yupp - wikipedia agrees PIC is right. 

![image](https://user-images.githubusercontent.com/126800229/224013617-b90ab2b8-e1bb-4c9a-9b48-5042b2597f14.png)

I'm just asking for HETU to be added into the documentation as a synonym for easy searching. (PIC "Also abbreviated as HETU")
