### ISSUE TITLE
Couldn't Patient.InterpreterRequired be inferred by Patient.communication.language?

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#87]
[Patient.InterpreterRequired](http://hl7.org/fhir/R4/extension-patient-interpreterrequired.html)

Couldn't this be instead represented by [Patient.communication.language](http://hl7.org/fhir/R4/patient-definitions.html#Patient.communication.language)?

This is more portable, and I think could accomplish the same logic. If language =/= local language, interpreter needed.

Open to being convinced on this one - maybe there's some specifics in operations that make sense (e.g. every non-Finnish speaker doesn't need an interpreter so this should be documented separately)

**Comment by mrinnetmaki** [comment]
I'm not an expert on how this field is used throughout the healthcare system, but the case I think of immediately is sign languages.

**Comment by jpriebe-epic** [comment]
I'd think Sign language could qualify as a language in one of the FHIR sets. 

I do see we store "needs interpreter" separately in the Epic database so this wouldn't be that hard to support

**Comment by mrinnetmaki** [comment]
Epic has a field in their database for this, but it is not expressed in FHIR, at least in the Patient resource.

**Comment by jpriebe-epic** [comment]
Ok with leaving as-is
