### ISSUE TITLE
Provenance register elements can probably be covered by standards

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-base-profiles#88]
[Provenance](https://build.fhir.org/ig/fhir-fi/finnish-base-profiles/branches/master/StructureDefinition-fi-base-provenance.html) 

![image](https://user-images.githubusercontent.com/126800229/224036366-ef95a07d-f044-4976-bc39-b37f391ac511.png)

[Register-type-code](https://build.fhir.org/ig/fhir-fi/finnish-base-profiles/branches/master/StructureDefinition-register-type-code.html)
[Register-specifier](https://build.fhir.org/ig/fhir-fi/finnish-base-profiles/branches/master/StructureDefinition-register-specifier.html)

These two elements I'm pretty sure can be handled in the standard FHIR models. I think this could be covered by a link to the register via [onBehalfOf](http://hl7.org/fhir/R4/provenance-definitions.html#Provenance.agent.onBehalfOf)

The larger question is probably how to represent a "register" in Finland. Probably extensions in each resource aren't the right way, but maybe a profiled Organization resource can handle this?

**Comment by mrinnetmaki** [comment]
@mikajylha to provide the links to the definitions of the required specifiers.

**Comment by mrinnetmaki** [comment]
Use case is SMART App Launch between Esko and Una. Una requires this info in launch.

**Comment by mrinnetmaki** [comment]
This might be useful: https://yhteistyotilat.fi/wiki08/pages/viewpage.action?pageId=64433645

**Comment by jpriebe-epic** [comment]
For Provenance use case of doing a SMART - do you have an example of how FHIR Provenance data would look from both perspectives, client and server?

|

_Actor_ Requests Patient Resource from **Custodian**

|


_Actor_

GET fhir.com/Patient/ID1234

In HTTP-land, a GET is not supposed to have a body, so doesn't really make sense to send Provenance FHIR data here generically for FHIR read operations. But the server needs to know who's querying and their justification right, that's the point of the register stuff? I guess if you're bundling FHIR Resources in some application later it can just be a POST or something.

Also, Isn't there a bunch of user info in the OAuth2 token? And the goal is checking the client to make sure they can access the server's register, could that be handled upstream of FHIR like in the authorization flow (e.g. in Oauth2, you request access to a SCOPE of X register that gets included in the JWT token)?

But if you did include Provenance resource here on the query side, it'd something like this:


{provenance...
...AGENT...= Actor identifiers (etc etc)"
...REGISTER/Target...=Register you're requesting access to
/provenance}

|

**Custodian**

Serves data from .../Patient/ID1234

{patient ... /patient}


|

"Query of Register Custodian" is a use case that I have a hunch will be repeated all over for queries to Kanta data/other patient data accessed through integration. In Apotti we see it all over in in Kanta queries, Radiology image queries from Kvarkki, and document management stuff. So important we get it right.

**Comment by jpriebe-epic** [comment]
Ping, maybe we can talk about this in a meeting - very curious about what this will look like (I might have it wrong in my example above)

**Comment by jpriebe-epic** [comment]
@mrinnetmaki any update, can we have a meeting to discuss this? Very curious about how this regulation will get implemented in the standards

**Comment by mrinnetmaki** [comment]
@jpriebe-epic sure! Most of Finland is on summer holidays right now. We could schedule this for our meeting on August 24. If that's too late for you, we can have an offline discussion sooner.

**Comment by mrinnetmaki** [comment]
To me, the use case is not so much access control (GET requests). I believe that will be handled differently.

What we mainly need this custodian info for is the peculiar Kanta. We store a lot of data there, but Kanta is usually not considered a custodian of the data. Therefore, it is important to store, together with the data, information on the actual custodian. So that if you for instance find some errors in the data you know whom to contact to get it corrected.

It's more about "who's responsible for maintaining this data" rather than "who has justified access to this data under these circumstances."

This is just my own view and does not necessarily reflect the view of the whole Finnish FHIR community, though.

**Comment by mrinnetmaki** [comment]
The same with Apotti, I guess. The system stores data from multiple register custodians, and it is useful for apps to be able to find out where a piece of data originates from.

My own hunch would be that access control would live on a different level (more generic, which practitioner in which role has access to which data) and that information could be reflected on integration layer too. You may want to implement that with the Provenance resource for any FHIR resources, but I don't think you'd be expected to. The same rules govern access to all data, not just the data that's available as FHIR resources.

And again, for both patients and practitioners it is sometimes useful to know where a piece of data originates from and who is responsible for maintaining it.

**Comment by mrinnetmaki** [comment]
It's of course plausible that you *want* to limit a query (A kanta query, for instance) to data from a certain register custodian. I don't know whether Kanta people already have a view on how this would look like. Perhaps @mikatuomainen does?

**Comment by jpriebe-epic** [comment]
Reading this again with your information and the goal of Provenance to represent the _register ownership of data_:

Similar to my comment in the [other issue](https://github.com/fhir-fi/finnish-base-profiles/issues/86) - I think "registers" can be represented as _Organization_ resources linked to from Provenance. This is close to how this data exists in Apotti today and how we support Finland's register privacy requirements. 

_provenance-participant-type_ specifically supports a participant type of ["custodian"](https://terminology.hl7.org/2.1.0/CodeSystem-provenance-participant-type.html) which sounds like exactly what we want to represent here. 

So register should be represented an Organization, pointed to via _Provenance.agent.type(custodian).who_

An example Provenance of a patient returned to accomplish the goal of Finnish register custodians:

```
         <Provenance>
              <target>
                  <reference value="Patient/TnOZ.elPXC6zcBNFMcFA7A5KZbYxo2.4T-LylRk4GoW4B" />
              </target>
              <recorded value="2019-05-28T14:07:06Z" />
              <agent>
                  <type>
                      <coding>
                          <system value="http://terminology.hl7.org/CodeSystem/provenance-participant-type" />
                          <code value="custodian" />
                          <display value="custodian" />
                      </coding>
                      <text value="custodian" />
                  </type>
                  <who>
                      <reference value="Organization/eyMDh2ar2p-q23sgasddhd61831083-8VWo3" />
                      <display value="VAKE Register" />
                  </who>
              </agent>
          </Provenance>

```

In this example I assume the register is the FHIR server generating the resource , so it's represented as _Provenance.who_. But an EHR FHIR client such as Epic might use _Provenance.agent.onBehalfOf_ to represent archiving data to the register, with Provenance.agent.who being representing the submitting organization.

Both already link to _FI Base Organization_, it's just a matter of moving the RegisterTypeCode and RegisterSpecifier to content in the Organization resource. RegisterTypeCode can probably be an identifier slice, RegisterSpecifier might need to be an extension.

If we decide to go this direction, I think example Organization resources representing each of the types would be helpful (Organization as Municipality, Organization as Register, Organization as Hospital).

Also I would like to hear what the Kanta and THL folks think about this, since it's their implementation that matters.

**Comment by jpriebe-epic** [comment]
Looks like Kela folks might agree with this change:
[Issue 141](https://github.com/fhir-fi/finnish-base-profiles/issues/141)

**Comment by mrinnetmaki** [comment]
Thanks @jpriebe-epic!

What we want to reference here is not just the organization. An organization may have several different registers.

The information required for Kanta includes
* the organization (*rekisterinpitäjä*)
* the register (*rekisteri*, might be "*työterveyshuolto*", person information register for occupational healthcare)
* the register specifier (*tarkenne*, the employer of the patient in the case of occupational healthcare)

To me, it feels a bit funny to have these extensions be in the Organization, because then you'd need several instances of the organization, one for each register they are maintaining and for each customer in their register for occupational health...

It also makes it a bit more tricky for a client to get this information...

**Comment by mrinnetmaki** [comment]
See some further discussion in https://chat.fhir.org/#narrow/stream/179247-Security-and-Privacy/topic/Specific.20register.20in.20Provenance/near/385441326.

**Comment by jpriebe-epic** [comment]
Pull request: https://github.com/fhir-fi/finnish-base-profiles/pull/166

Talked with Mikael - the new model seems to make more sense

I think this change satisfies me, but I want to do a deeper review to make sure I understand.

**Comment by mrinnetmaki** [comment]
Thanks Josh!

**Comment by mrinnetmaki** [comment]
We got pretty close to a solution, but failed to reach consensus. Register type and register specifier were left out of the v1.0.0. The proposal for including the info in `.entity` is still there, but commented out. See #172.
