### ISSUE TITLE
Clean up the QA report

### ISSUE THREAD

**Issue by mrinnetmaki** [fhir-fi/finnish-base-profiles#95]
Let's work though all of the issues in the QA report (https://fhir.fi/finnish-base-profiles/qa.html) and fix as much as we can.

One way to clean it up is to just hide the errors. See #94. However, that should never be the first option.

We need to discuss what to do with the examples imported from Kanta PHR. They have quite a few errors. I'm guessing it could be nice to leave some information on these visible in this implementation guide, so implementers could have a way to evaluate how much they should trust any particular example. Any other views?

**Comment by mikajylha** [comment]
#91 contains fixes for condition examples

**Comment by mrinnetmaki** [comment]
Also #93 does a bit of cleaning up.

**Comment by mrinnetmaki** [comment]
All errors now have an explanation in the guide.
